# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20151104_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('workshop', 'workshop'), ('webinar', 'webinar'), ('lecture', 'lecture')], default='workshop', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='details',
            field=markupfield.fields.MarkupField(blank=True, default=None, help_text='Edit in Markdown', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='details_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='result',
            field=models.CharField(blank=True, choices=[('SC', 'Satisfactory Completion'), ('I', 'Incomplete'), ('RE', 'Registered, but Never Attended'), ('AT', 'Attendance Verfied'), ('W', 'Withdrawn')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pubtype',
            field=models.CharField(choices=[('blog', 'blog'), ('tutorial', 'tutorial'), ('paper', 'paper'), ('slides', 'slides'), ('book', 'book')], default='blog', max_length=12),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='details',
            field=markupfield.fields.MarkupField(blank=True, default=None, help_text='Edit in Markdown', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='details_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
