# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20151104_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=markupfield.fields.MarkupField(blank=True, default=None, help_text='Edit in Markdown', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='details',
            field=markupfield.fields.MarkupField(blank=True, default=None, help_text='Edit in Markdown', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='details_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
